import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    dir: "ltr",
    lang: "en",
    nav: {
      home: "Home",
      about: "About",
      gallery: "Gallery",
      services: "Services",
      process: "Process",
      // reviews: 'Reviews',
      contact: "Contact",
    },
    hero: {
      tagline: "Where Ink Meets Eternity",
      heading1: "The Art of",
      heading2: "Calligraphy",
      subheading:
        "Breathing Life into Words By Faisal Ansari, Arabic & Islamic Calligrapher, Bangalore",
      cta: "Explore My Work",
    },
    about: {
      sectionLabel: "About the Artist",
      heading: "Mastering the Ancient Art",
      subheading:
        "A lifelong dedication to the living tradition of Arabic script",
      p1: "I, Faisal Ansari, have dedicated years to learning and practicing this art. My journey has been guided by my teacher Ustaad Mukhtar ahmad Sahib, supported by my parents, my wife, my brothers and friends. It took almost five years of constant practice to master the major Arabic scripts — Thuluth, Naskh, and Nastaliq.",
      p2: "During the day, I worked for my livelihood; at night, I immersed myself in letters, often spending hours perfecting a single curve. Every weekend, I would meet my teacher for lessons — a routine that shaped my artistic discipline and inner peace.",
      badge: "9+ Years of Mastery",
      stylesLabel: "Calligraphy Styles",
      styles: ["Naskh", "Thuluth", "Nastaliq", "Ruq'ah"],
      mediumsLabel: "Mediums",
      mediums: ["Fine Paper", "Glass", "Wood"],
    },
    gallery: {
      sectionLabel: "Portfolio",
      heading: "A Gallery of Living Words",
      subheading: "Each piece a story — each letter a journey through time",
      filters: ["All", "Thuluth", "Naskh", "Ruq'ah", "Nastaliq"],
      items: [
        {
          id: 1,
          title: "Bismillah — Thuluth",
          subtitle: "Gold on Black Velvet",
          style: "Thuluth",
          arabic: "بِسْمِ اللهِ",
          url: "/image/01.jpg",
        },
        {
          id: 2,
          title: "Bismillah — Thuluth",
          subtitle: "Gold on Black Velvet",
          style: "Thuluth",
          arabic: "بِسْمِ اللهِ",
          url: "/image/01.jpg",
        },
        {
          id: 3,
          title: "Al-Fatiha — Naskh",
          subtitle: "Ink on Handmade Paper",
          style: "Naskh",
          arabic: "الفاتحة",
          url: "/image/01.jpg",
        },
        {
          id: 4,
          title: "Al-Fatiha — Naskh",
          subtitle: "Ink on Handmade Paper",
          style: "Naskh",
          arabic: "الفاتحة",
          url: "/image/01.jpg",
        },
        {
          id: 5,
          title: "Rumi Poem — Nastaliq",
          subtitle: "Saffron & Indigo",
          style: "Nastaliq",
          arabic: "شعر رومي",
          url: "/image/01.jpg",
        },
        {
          id: 6,
          title: "Rumi Poem — Nastaliq",
          subtitle: "Saffron & Indigo",
          style: "Nastaliq",
          arabic: "شعر رومي",
          url: "/image/01.jpg",
        },
        {
          id: 7,
          title: "Wedding Panel — Thuluth",
          subtitle: "Gold Leaf on Linen",
          style: "Thuluth",
          arabic: "مبروك",
          url: "/image/01.jpg",
        },
        {
          id: 8,
          title: "Wedding Panel — Thuluth",
          subtitle: "Gold Leaf on Linen",
          style: "Thuluth",
          arabic: "مبروك",
          url: "/image/01.jpg",
        },
      ],
    },
    services: {
      sectionLabel: "Services",
      heading: "Crafted for Every Occasion",
      subheading: "Bespoke calligraphy services tailored to your vision",
      items: [
        {
          icon: "💌",
          name: "Wedding Invitations",
          desc: "Handcrafted bilingual invitations that set the tone for your most important day.",
          price: "From $150",
          tag: "Most Popular",
        },
        {
          icon: "🖼️",
          name: "Artwork Panels",
          desc: "Original calligraphy art on canvas, paper, or wood — a statement for any wall.",
          price: "From $200",
          tag: "",
        },
        {
          icon: "📜",
          name: "Certificates & Diplomas",
          desc: "Formal calligraphy for certificates, awards, and commemorative documents.",
          price: "From $80",
          tag: "",
        },
        {
          icon: "✍️",
          name: "Logo & Brand Identity",
          desc: "Arabic calligraphy logos and wordmarks for businesses seeking cultural elegance.",
          price: "From $300",
          tag: "Premium",
        },
        {
          icon: "🎁",
          name: "Personalized Gifts",
          desc: "Names, poems, and quotes rendered in gold — the perfect timeless gift.",
          price: "From $60",
          tag: "",
        },
        {
          icon: "🏛️",
          name: "Workshops",
          desc: "Learn the basics of Naskh or Thuluth script in intimate group or private sessions.",
          price: "From $120",
          tag: "New",
        },
      ],
    },
    process: {
      sectionLabel: "How It Works",
      heading: "From Vision to Masterpiece",
      subheading: "A refined five-step journey to your perfect commission",
      steps: [
        {
          num: "01",
          title: "Consultation",
          desc: "We discuss your vision, text, preferred style, and medium during a free discovery call.",
        },
        {
          num: "02",
          title: "Design",
          desc: "I create initial layout sketches and propose compositions for your approval.",
        },
        {
          num: "03",
          title: "Refinement",
          desc: "Two rounds of revisions ensure every detail matches your expectations perfectly.",
        },
        {
          num: "04",
          title: "Creation",
          desc: "The final piece is meticulously handcrafted using traditional tools and premium materials.",
        },
        {
          num: "05",
          title: "Delivery",
          desc: "Your artwork is carefully packaged and shipped worldwide with a certificate of authenticity.",
        },
      ],
    },
    testimonials: {
      sectionLabel: "Testimonials",
      heading: "Words from Patrons",
      subheading:
        "Every commission is a relationship built on trust and artistry",
      items: [
        {
          name: "Sara Al-Rashid",
          location: "Dubai, UAE",
          text: "The wedding calligraphy was breathtaking. Our guests could not stop admiring it. Truly a master of his craft.",
          rating: 5,
        },
        {
          name: "James Whitfield",
          location: "London, UK",
          text: "I commissioned an Arabic verse for my study. The work arrived beautifully framed and exceeded every expectation.",
          rating: 5,
        },
        {
          name: "Layla Hassan",
          location: "Cairo, Egypt",
          text: "Perfect execution of the Thuluth script for our family heirloom. The attention to detail is extraordinary.",
          rating: 5,
        },
        {
          name: "Marco Rossi",
          location: "Milan, Italy",
          text: "Our brand identity now carries a beautiful Arabic wordmark. Clients love the authenticity and cultural depth.",
          rating: 5,
        },
      ],
    },
    contact: {
      sectionLabel: "Get in Touch",
      heading: "Begin Your Commission",
      subheading: "Let's bring your vision to life — one letter at a time",
      namePlaceholder: "Your Name",
      emailPlaceholder: "Your Email",
      phonePlaceholder: "Phone (optional)",
      projectLabel: "Project Type",
      messagePlaceholder: "Tell me about your project...",
      submit: "Send Message",
      projectTypes: [
        "Wedding Invitations",
        "Artwork Panel",
        "Certificate",
        "Logo / Brand",
        "Personalized Gift",
        "Workshop",
        "Other",
      ],
      successTitle: "Message Sent!",
      successMsg: "Thank you for reaching out. I'll reply within 24 hours.",
      sendAnother: "Send Another Message",
    },
    footer: {
      tagline: "Where ancient tradition meets contemporary artistry.",
      quickLinks: "Quick Links",
      newsletter: "Stay Inspired",
      newsletterDesc:
        "Subscribe for calligraphy insights, new works, and exclusive offers.",
      emailPlaceholder: "faisalart08@gmail.com",
      subscribe: "Subscribe",
      copyright: "© 2026 DACC. All rights reserved.",
      madeWith: "Crafted with ink & soul",
    },
  },

  ar: {
    dir: "rtl",
    lang: "ar",
    nav: {
      home: "الرئيسية",
      about: "عن الفنان",
      gallery: "المعرض",
      services: "الخدمات",
      process: "المراحل",
      // reviews: 'التقييمات',
      contact: "تواصل معنا",
    },
    hero: {
      tagline: "حيث يلتقي الحبر بالخلود",
      heading1: "فن",
      heading2: "الخط العربي",
      subheading:
        "إحياء الكلمات بالحياة — بقلم فيصل أنصاري، خطاط عربي وإسلامي، بنغالور",
      cta: "استكشف أعمالي",
    },
    about: {
      sectionLabel: "عن الفنان",
      heading: "إتقان فن الخط الأصيل",
      subheading: "تفانٍ مدى الحياة في التراث الحي للخط العربي",
      p1: "أنا فيصل أنصاري، كرّست سنواتٍ لتعلم هذا الفن وممارسته. كانت رحلتي بتوجيه من أستاذي الأستاذ مختار أحمد صاحب، وبدعم من والديّ وزوجتي وإخوتي وأصدقائي. استغرق الأمر قرابة خمس سنوات من الممارسة المتواصلة لإتقان الخطوط العربية الكبرى — الثلث، والنسخ، والنستعليق.",
      p2: "في النهار كنت أعمل لكسب رزقي، وفي الليل كنت أنغمس في الحروف، أقضي ساعاتٍ في إتقان منحنى واحد. كل عطلة أسبوعية كنت أذهب إلى أستاذي للدروس — روتينٌ شكّل انضباطي الفني وطمأنينتي الداخلية.",
      badge: "أكثر من ٩ سنوات من الإتقان",
      stylesLabel: "أنماط الخط",
      styles: ["النسخ", "الثلث", "النستعليق", "الرقعة"],
      mediumsLabel: "الوسائط",
      mediums: ["ورق فاخر", "زجاج", "خشب"],
    },
    gallery: {
      sectionLabel: "المعرض",
      heading: "معرض الكلمات الحية",
      subheading: "كل لوحة حكاية — كل حرف رحلة عبر الزمن",
      filters: ["الكل", "الثلث", "النسخ", "الرقعة", "النستعليق"],
      items: [
        {
          id: 1,
          title: "البسملة — الثلث",
          subtitle: "ذهب على مخمل أسود",
          style: "Thuluth",
          arabic: "بِسْمِ اللهِ",
          url: "/image/01.jpg",
        },
        {
          id: 2,
          title: "البسملة — الثلث",
          subtitle: "ذهب على مخمل أسود",
          style: "Thuluth",
          arabic: "بِسْمِ اللهِ",
          url: "/image/01.jpg",
        },
        {
          id: 3,
          title: "الفاتحة — النسخ",
          subtitle: "حبر على ورق يدوي",
          style: "Naskh",
          arabic: "الفاتحة",
          url: "/image/01.jpg",
        },
        {
          id: 4,
          title: "الفاتحة — النسخ",
          subtitle: "حبر على ورق يدوي",
          style: "Naskh",
          arabic: "الفاتحة",
          url: "/image/01.jpg",
        },
        {
          id: 5,
          title: "شعر رومي — النستعليق",
          subtitle: "الزعفران والنيلي",
          style: "Nastaliq",
          arabic: "شعر رومي",
          url: "/image/01.jpg",
        },
        {
          id: 6,
          title: "شعر رومي — النستعليق",
          subtitle: "الزعفران والنيلي",
          style: "Nastaliq",
          arabic: "شعر رومي",
          url: "/image/01.jpg",
        },
        {
          id: 7,
          title: "لوحة عرس — الثلث",
          subtitle: "ورق الذهب على الكتان",
          style: "Thuluth",
          arabic: "مبروك",
          url: "/image/01.jpg",
        },
        {
          id: 8,
          title: "لوحة عرس — الثلث",
          subtitle: "ورق الذهب على الكتان",
          style: "Thuluth",
          arabic: "مبروك",
          url: "/image/01.jpg",
        },
      ],
    },
    services: {
      sectionLabel: "الخدمات",
      heading: "إبداع لكل مناسبة",
      subheading: "خدمات خط عربي حصرية مصممة وفق رؤيتك",
      items: [
        {
          icon: "💌",
          name: "دعوات الأفراح",
          desc: "دعوات ثنائية اللغة مكتوبة يدويًا تضع الأساس لأهم يوم في حياتك.",
          price: "يبدأ من ١٥٠$",
          tag: "الأكثر طلبًا",
        },
        {
          icon: "🖼️",
          name: "اللوحات الفنية",
          desc: "فن خط أصيل على قماش أو ورق أو خشب — تحفة لأي جدار.",
          price: "يبدأ من ٢٠٠$",
          tag: "",
        },
        {
          icon: "📜",
          name: "الشهادات والدبلومات",
          desc: "خط رسمي للشهادات والجوائز والوثائق التذكارية.",
          price: "يبدأ من ٨٠$",
          tag: "",
        },
        {
          icon: "✍️",
          name: "الشعار وهوية العلامة",
          desc: "شعارات خطية وعلامات تجارية بالخط العربي لمن يسعى للأناقة الثقافية.",
          price: "يبدأ من ٣٠٠$",
          tag: "مميز",
        },
        {
          icon: "🎁",
          name: "الهدايا الشخصية",
          desc: "أسماء وقصائد ومقتطفات بالذهب — الهدية الخالدة المثالية.",
          price: "يبدأ من ٦٠$",
          tag: "",
        },
        {
          icon: "🏛️",
          name: "ورش العمل",
          desc: "تعلّم أساسيات النسخ أو الثلث في جلسات جماعية أو خاصة.",
          price: "يبدأ من ١٢٠$",
          tag: "جديد",
        },
      ],
    },
    process: {
      sectionLabel: "آلية العمل",
      heading: "من الرؤية إلى التحفة",
      subheading: "رحلة مكونة من خمس مراحل نحو لوحتك المثالية",
      steps: [
        {
          num: "٠١",
          title: "الاستشارة",
          desc: "نتحدث عن رؤيتك والنص والأسلوب المفضل والوسيط خلال مكالمة مجانية.",
        },
        {
          num: "٠٢",
          title: "التصميم",
          desc: "أُعدّ رسومات أولية وأقترح تكوينات بصرية لموافقتك.",
        },
        {
          num: "٠٣",
          title: "التنقيح",
          desc: "جولتان من المراجعة لضمان تطابق كل تفصيل مع توقعاتك.",
        },
        {
          num: "٠٤",
          title: "الإنجاز",
          desc: "تُصنع اللوحة النهائية بعناية باستخدام أدوات تقليدية ومواد فاخرة.",
        },
        {
          num: "٠٥",
          title: "التسليم",
          desc: "يُعبَّأ عملك الفني بعناية ويُشحن دوليًا مع شهادة أصالة.",
        },
      ],
    },
    testimonials: {
      sectionLabel: "آراء العملاء",
      heading: "كلمات من رعاة الفن",
      subheading: "كل لوحة علاقة مبنية على الثقة والإبداع",
      items: [
        {
          name: "سارة الراشد",
          location: "دبي، الإمارات",
          text: "كان خط الزفاف رائعًا. لم يتوقف ضيوفنا عن الإعجاب به. إنه حقًا أستاذ في فنه.",
          rating: 5,
        },
        {
          name: "جيمس ويتفيلد",
          location: "لندن، المملكة المتحدة",
          text: "طلبت بيت شعر عربيًا لمكتبتي. وصل العمل معبأً بشكل جميل وفاق كل توقعاتي.",
          rating: 5,
        },
        {
          name: "ليلى حسن",
          location: "القاهرة، مصر",
          text: "تنفيذ مثالي لخط الثلث في إرثنا العائلي. الاهتمام بالتفاصيل لا مثيل له.",
          rating: 5,
        },
        {
          name: "ماركو روسي",
          location: "ميلان، إيطاليا",
          text: "أصبحت هوية علامتنا التجارية تحمل علامة خطية عربية جميلة. العملاء يعشقون الأصالة.",
          rating: 5,
        },
      ],
    },
    contact: {
      sectionLabel: "تواصل معنا",
      heading: "ابدأ طلبك",
      subheading: "دعنا نحوّل رؤيتك إلى واقع — حرفًا بحرف",
      namePlaceholder: "اسمك",
      emailPlaceholder: "بريدك الإلكتروني",
      phonePlaceholder: "الهاتف (اختياري)",
      projectLabel: "نوع المشروع",
      messagePlaceholder: "أخبرني عن مشروعك...",
      submit: "إرسال الرسالة",
      projectTypes: [
        "دعوات أفراح",
        "لوحة فنية",
        "شهادة",
        "شعار تجاري",
        "هدية شخصية",
        "ورشة عمل",
        "أخرى",
      ],
      successTitle: "تم الإرسال!",
      successMsg: "شكرًا لتواصلك. سأردّ في غضون ٢٤ ساعة.",
      sendAnother: "إرسال رسالة أخرى",
    },
    footer: {
      tagline: "حيث يلتقي التراث العريق بالإبداع المعاصر.",
      quickLinks: "روابط سريعة",
      newsletter: "ابقَ ملهمًا",
      newsletterDesc: "اشترك لتلقّي رؤى الخط وأعمال جديدة وعروض حصرية.",
      emailPlaceholder: "faisalart08@gmail.com",
      subscribe: "اشتراك",
      copyright: "© ٢٠٢٦ DACC. جميع الحقوق محفوظة.",
      madeWith: "صُنع بالحبر والروح",
    },
  },

  ur: {
    dir: "rtl",
    lang: "ur",
    nav: {
      home: "صفحہ اول",
      about: "فنکار کے بارے میں",
      gallery: "گیلری",
      services: "خدمات",
      process: "مراحل",
      // reviews: 'تبصرے',
      contact: "رابطہ",
    },
    hero: {
      tagline: "جہاں روشنائی ابدیت سے ملتی ہے",
      heading1: "فن",
      heading2: "عربی خطاطی",
      subheading:
        "الفاظ میں زندگی پھونکنا — از فیصل انصاری، عربی و اسلامی خطاط، بنگلور",
      cta: "میرے کام دیکھیں",
    },
    about: {
      sectionLabel: "فنکار کے بارے میں",
      heading: "قدیم فن میں مہارت",
      subheading: "عربی خط کی زندہ روایت سے تاحیات وابستگی",
      p1: "میں فیصل انصاری، نے سال اس فن کو سیکھنے اور مشق کرنے میں وقف کیے ہیں۔ میرا سفر میرے استاذ، استاذ مختار احمد صاحب کی رہنمائی میں طے ہوا، اور میرے والدین، میری اہلیہ، میرے بھائیوں اور دوستوں کی حمایت سے ممکن ہوا۔ بڑے عربی خطوط — ثلث، نسخ، اور نستعلیق — پر عبور حاصل کرنے میں تقریباً پانچ سال کی مسلسل مشق لگی۔",
      p2: "دن کو میں روزی کماتا، رات کو حروف میں ڈوب جاتا، اکثر ایک ہی خم کو گھنٹوں نکھارتا رہتا۔ ہر ہفتے کے اختتام پر استاذ سے سبق لیتا — یہ معمول میرے فنی نظم اور اندرونی سکون کا سبب بنا۔",
      badge: "٩+ سال کی مہارت",
      stylesLabel: "خطاطی کے انداز",
      styles: ["نسخ", "ثلث", "نستعلیق", "رقعہ"],
      mediumsLabel: "ذرائع",
      mediums: ["عمدہ کاغذ", "شیشہ", "لکڑی"],
    },
    gallery: {
      sectionLabel: "پورٹ فولیو",
      heading: "زندہ الفاظ کی گیلری",
      subheading: "ہر لوحہ ایک کہانی — ہر حرف وقت کے پار سفر",
      filters: ["سب", "ثلث", "نسخ", "رقعہ", "نستعلیق"],
      items: [
        {
          id: 1,
          title: "بسم اللہ — ثلث",
          subtitle: "سیاہ مخمل پر سونا",
          style: "Thuluth",
          arabic: "بِسْمِ اللهِ",
          url: "/image/01.jpg",
        },
        {
          id: 2,
          title: "بسم اللہ — ثلث",
          subtitle: "سیاہ مخمل پر سونا",
          style: "Thuluth",
          arabic: "بِسْمِ اللهِ",
          url: "/image/01.jpg",
        },
        {
          id: 3,
          title: "الفاتحہ — نسخ",
          subtitle: "دستی کاغذ پر روشنائی",
          style: "Naskh",
          arabic: "الفاتحة",
          url: "/image/01.jpg",
        },
        {
          id: 4,
          title: "الفاتحہ — نسخ",
          subtitle: "دستی کاغذ پر روشنائی",
          style: "Naskh",
          arabic: "الفاتحة",
          url: "/image/01.jpg",
        },
        {
          id: 5,
          title: "رومی کا شعر — نستعلیق",
          subtitle: "زعفران اور نیلا",
          style: "Nastaliq",
          arabic: "شعر رومي",
          url: "/image/01.jpg",
        },
        {
          id: 6,
          title: "رومی کا شعر — نستعلیق",
          subtitle: "زعفران اور نیلا",
          style: "Nastaliq",
          arabic: "شعر رومي",
          url: "/image/01.jpg",
        },
        {
          id: 7,
          title: "شادی لوح — ثلث",
          subtitle: "کتان پر سونے کا ورق",
          style: "Thuluth",
          arabic: "مبروك",
          url: "/image/01.jpg",
        },
        {
          id: 8,
          title: "شادی لوح — ثلث",
          subtitle: "کتان پر سونے کا ورق",
          style: "Thuluth",
          arabic: "مبروك",
          url: "/image/01.jpg",
        },
      ],
    },
    services: {
      sectionLabel: "خدمات",
      heading: "ہر موقع کے لیے فن",
      subheading: "آپ کے تصور کے مطابق خصوصی خطاطی خدمات",
      items: [
        {
          icon: "💌",
          name: "شادی کی دعوت نامے",
          desc: "دو لسانی ہاتھ سے لکھے دعوت نامے جو آپ کے اہم دن کی تیاری کراتے ہیں۔",
          price: "١٥٠$ سے",
          tag: "سب سے مقبول",
        },
        {
          icon: "🖼️",
          name: "آرٹ لوحات",
          desc: "کینوس، کاغذ یا لکڑی پر اصل خطاطی آرٹ — کسی بھی دیوار کے لیے۔",
          price: "٢٠٠$ سے",
          tag: "",
        },
        {
          icon: "📜",
          name: "اسناد و ڈپلومے",
          desc: "سرکاری تقریبات، اعزازات اور یادگاری دستاویزات کے لیے خطاطی۔",
          price: "٨٠$ سے",
          tag: "",
        },
        {
          icon: "✍️",
          name: "لوگو اور برانڈ",
          desc: "ثقافتی خوبصورتی کے خواہاں کاروباروں کے لیے عربی خطاطی لوگو۔",
          price: "٣٠٠$ سے",
          tag: "پریمیم",
        },
        {
          icon: "🎁",
          name: "ذاتی تحائف",
          desc: "سونے میں نام، اشعار اور اقتباسات — بہترین لازوال تحفہ۔",
          price: "٦٠$ سے",
          tag: "",
        },
        {
          icon: "🏛️",
          name: "ورکشاپس",
          desc: "نسخ یا ثلث خط کی بنیادی تعلیم، گروپ یا نجی نشستوں میں۔",
          price: "١٢٠$ سے",
          tag: "نیا",
        },
      ],
    },
    process: {
      sectionLabel: "طریقہ کار",
      heading: "تصور سے شاہکار تک",
      subheading: "آپ کے کمیشن کے لیے پانچ مرحلوں کا سفر",
      steps: [
        {
          num: "۰١",
          title: "مشاورت",
          desc: "مفت کال میں آپ کا تصور، متن، پسندیدہ انداز اور ذریعہ زیرِ بحث آتا ہے۔",
        },
        {
          num: "۰٢",
          title: "ڈیزائن",
          desc: "ابتدائی خاکے اور ترکیبی تجاویز آپ کی منظوری کے لیے پیش کی جاتی ہیں۔",
        },
        {
          num: "۰٣",
          title: "اصلاح",
          desc: "دو بار نظرثانی سے یہ یقینی بنایا جاتا ہے کہ ہر تفصیل آپ کی توقعات سے مطابقت رکھے۔",
        },
        {
          num: "۰٤",
          title: "تخلیق",
          desc: "آخری لوحہ روایتی اوزاروں اور اعلیٰ مواد سے احتیاط سے بنایا جاتا ہے۔",
        },
        {
          num: "۰٥",
          title: "ترسیل",
          desc: "آپ کا فن پارہ احتیاط سے پیک کر کے اصالت کے سرٹیفکیٹ کے ساتھ عالمی سطح پر بھیجا جاتا ہے۔",
        },
      ],
    },
    testimonials: {
      sectionLabel: "تبصرے",
      heading: "سرپرستوں کے الفاظ",
      subheading: "ہر کمیشن اعتماد اور فنکاری پر مبنی رشتہ ہے",
      items: [
        {
          name: "سارہ الراشد",
          location: "دبئی، یو اے ای",
          text: "شادی کی خطاطی دیکھ کر آنکھیں خیرہ ہو گئیں۔ مہمان تعریف کرتے نہ تھکے۔ واقعی اپنے فن کا استاد ہے۔",
          rating: 5,
        },
        {
          name: "جیمز وائٹ فیلڈ",
          location: "لندن، برطانیہ",
          text: "اپنی لائبریری کے لیے عربی شعر کا آرڈر دیا۔ خوبصورت فریم کے ساتھ آیا اور توقعات سے بڑھ کر تھا۔",
          rating: 5,
        },
        {
          name: "لیلیٰ حسن",
          location: "قاہرہ، مصر",
          text: "خاندانی ورثے کے لیے ثلث خط کا بے مثال نمونہ۔ باریکیوں پر توجہ لاجواب ہے۔",
          rating: 5,
        },
        {
          name: "مارکو روسی",
          location: "میلان، اٹلی",
          text: "ہماری برانڈ شناخت میں ایک خوبصورت عربی نام اب موجود ہے۔ گاہک اصالت اور ثقافتی گہرائی پسند کرتے ہیں۔",
          rating: 5,
        },
      ],
    },
    contact: {
      sectionLabel: "رابطہ کریں",
      heading: "اپنا کمیشن شروع کریں",
      subheading: "آئیں آپ کے تصور کو حقیقت میں ڈھالیں — ایک حرف سے",
      namePlaceholder: "آپ کا نام",
      emailPlaceholder: "آپ کا ای میل",
      phonePlaceholder: "فون (اختیاری)",
      projectLabel: "منصوبے کی قسم",
      messagePlaceholder: "اپنے منصوبے کے بارے میں بتائیں...",
      submit: "پیغام بھیجیں",
      projectTypes: [
        "شادی کی دعوتیں",
        "آرٹ لوحہ",
        "سند",
        "لوگو / برانڈ",
        "ذاتی تحفہ",
        "ورکشاپ",
        "دیگر",
      ],
      successTitle: "پیغام بھیج دیا گیا!",
      successMsg: "رابطہ کرنے کا شکریہ۔ میں ٢٤ گھنٹوں کے اندر جواب دوں گا۔",
      sendAnother: "ایک اور پیغام بھیجیں",
    },
    footer: {
      tagline: "جہاں قدیم روایت جدید فنکاری سے ملتی ہے۔",
      quickLinks: "فوری لنکس",
      newsletter: "متاثر رہیں",
      newsletterDesc:
        "خطاطی کی جھلکیاں، نئے کام اور خصوصی پیشکشیں پانے کے لیے سبسکرائب کریں۔",
      emailPlaceholder: "faisalart08@gmail.com",
      subscribe: "سبسکرائب",
      copyright: "© ٢٠٢٦ DACC. جملہ حقوق محفوظ ہیں۔",
      madeWith: "روشنائی اور روح سے تخلیق کیا گیا",
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en");
  const t = translations[language];
  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t, translations }}
    >
      <div dir={t.dir} lang={t.lang}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
